name = "LeanForth"
version = "0.1.0"
defaultTargets = ["leanforth"]
srcDir = "src"

[[lean_lib]]
name = "LeanForth"

[[lean_exe]]
name = "leanforth"
root = "Main"

[[lean_exe]]
name = "test"
root = "Test"
